# Generated by Django 4.2.6 on 2025-06-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='job_description',
            field=models.TextField(null=True),
        ),
    ]
